name: Python CI

on: [push, pull_request]

jobs: 
  build:

    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
  
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
  
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r wymagania.txt
  
    - name: Run tests
      run: |
        pytest

    - name: Informacje
      run: |
        echo "💡the ${{ github.repository }} has been cloned to the runner ."
