  name: PostgreSQL Service
  on:
#uruchamiany kiedy chcemy
    workflow_dispatch:

  jobs:
    test_db:
      name: CheckService
      runs-on: ubuntu-latest
      services:
        postgres:
          image: postgres:15
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: testdb
          ports:
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-timeout 5s
      steps:
        - name: Check out repo code
          uses: actions/checkout@v3
        - name: Install Postgres client
          run: |
            sudo apt-get -yqq install postgres-client
        - name: Check postgres service
          env:
            PGPASSWORD: postgres
          run: |
            psql -h localhost -U postgres -d testdb -c 'SELECT version();'